spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labofitness
    username: postgres
    password : Dg3HIJ50__
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
